version: '3.1'
services:
  mysql:
    image: mysql:8
    volumes:
      - ./dbdata:/var/lib/mysql/
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bank
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
  java:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  db_data:
